config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show] do
    resources :items, only: [:index, :create, :edit, :update]
  end

  resources :items, param: :asin, only: [:show] do
    collection do
      get 'search'
    end
  end

  root 'home#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  has_many :tags
  accepts_nested_attributes_for :tags

  validates :user_id, :rank, :status, presence: true

  enum status_list: %i(-- 読みたい いま読んでる 読み終わった 積読)
  enum rank_list: %i(評価しない ★ ★★ ★★★ ★★★★ ★★★★★)
  enum category_list: %i(- 小説 ビジネス 自己啓発 技術 資格)

  def self.find_by_status(status)
    self.where({:status => status}).order('created_at desc')
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: %i{index search show create edit update}
  before_action :set_item, only: %i{edit update}
  before_action :set_book, only: %i{show}

  def index
    @items = current_user.items.order(created_at: :desc).page(params[:page])
  end

  def search
    @data = Book.search_for_amazon(params[:keyword], params[:page] ? params[:page].to_i : 1)
    @keyword = params[:keyword]
  end

  def show
  end

  def create
    @book = Book.find_or_create_by(book_paramas)
    @item = current_user.items.build({user_id: current_user.id, book_id: @book.id})
    @item.save!

    respond_to do |format|
      format.js
    end
  end

  def edit
  end

  def update
    if (@item.update(item_params))
      flash.notice = '更新しました'
      redirect_to user_items_path
    else
      flash.now.alert = '更新に失敗しました'
      render :edit
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_book
    @book = Book.find_or_create_by_asin(params[:asin])
  end

  def item_params
    params.require(:item).permit(:status, :rank, :category_id,
      :review, tags_attributes: [:id, :name])
  end

  def book_paramas
    params.require(:book).permit(:asin, :title, :author, :price, :publicated_at, :manufacturer, :image)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def set_books(res)
    books = []
    res.items.each do |item|
      element = item.get_element('ItemAttributes')
      asin = item.get('ASIN')
      book = {
          :asin             => asin,
          :title            => element.get('Title'),
          :author           => element.get_array('Author').join(', '),
          :manufacturer     => element.get('Manufacturer'),
          :publication_date => element.get('PublicationDate'),
          :price            => element.get('ListPrice/FormattedPrice'),
          :image            => item.get('LargeImage/URL'),
          :small_image      => item.get('SmallImage/URL'),
          :medium_image     => item.get('MediumImage/URL'),
      }
      books.push(book)
    end
    books
  end

  def set_pager(res)
    pager_data = {
        :books          => [],
        :current_page   => res.item_page,
        :total_pages    => [res.total_pages, 5].min,
        :total_results  => [res.total_results, 50].min,
        :limit          => 10
    }
    pager_data
  end
end

app/views/items/_form.html.haml
.row
  .well
    = simple_form_for @item, url: user_item_path , html: {class: 'form-horizontal'} do |f|
      .form-group
        = f.input :status, collection: Item.status_lists, include_blank: false,
            wrapper_html: { class: 'col-lg-4'}, input_html: {class: 'form-control'}, label: '読書状況'

      .form-group
        = f.input :rank, collection: Item.rank_lists, include_blank: false,
            wrapper_html: { class: 'col-lg-4'}, input_html: {class: 'form-control'}, label: '評価'

      .form-group
        = f.input :category_id, collection: Item.category_lists, include_blank: false,
            wrapper_html: { class: 'col-lg-4'}, input_html: {class: 'form-control'}, label: 'カテゴリ'

      .form-group
        = f.input :review, as: :text, required: false,
            wrapper_html: { class: 'col-lg-6'}, input_html: {class: 'form-control', cols:60, rows:5}, label: 'レビュー'

      .form-group
        - (5 - @item.tags.length).times {@item.tags.build}
        = f.fields_for :tags do |tag_field|
          = tag_field.input :name, required: false,
              wrapper_html: { class: 'col-lg-2'}, input_html: {class: 'form-control'}, label: "タグ#{tag_field.index+1}"
        .col-lg-12
      .form-group
        = f.button :submit, class: 'btn btn-primary', value: '編集'

app/views/items/_pager.html.haml
.row
  .col-lg-12
    %ul.pagination
      - if @pager_data[:current_page] == 1
        %li.disabled
          = link_to raw('&laquo;'), '#'
      - else
        %li
          = link_to raw('&laquo;'), search_items_path(keyword: @keyword, page: @pager_data[:current_page] - 1)
      - range = 1..@pager_data[:total_pages]
      - range.each do |num|
        - if num == @pager_data[:current_page]
          %li.active
            %a= num
        - else
          %li
            = link_to num, search_items_path(keyword: @keyword, page: num)
      - if @pager_data[:current_page] == @pager_data[:total_pages]
        %li.disabled
          = link_to raw('&raquo;'), '#'
      - else
        %li
          = link_to raw('&raquo;'), search_items_path(keyword: @keyword, page: @pager_data[:current_page] + 1)
    - start_number = (@pager_data[:current_page] - 1) * @pager_data[:limit] + 1
    - last_number = start_number + @pager_data[:limit] - 1
    - last_number = last_number > @pager_data[:total_results] ? @pager_data[:total_results] : last_number
    %p 全#{@pager_data[:total_results]}件中 #{start_number} - #{last_number}件を表示

app/views/items/create.js.erb
alert('登録完了しました');
$('#book_<%= @book.asin %> .result-form').html('本棚に登録済み');

app/views/items/edit.html.haml
.row
  = content_tag(:div, flash.alert, class: 'alert alert-danger') if flash.alert
  .page-header
    %h2 登録情報の編集
  .col-lg-2
    = image_tag medium_book_image(@item.book.image)
  .col-lg-7
    %p= link_to @item.book.title, item_path(@item.book.asin)
    %p= @item.book.author
%br
= render 'items/form'

app/views/items/index.html.haml
.row
  = content_tag(:div, flash.notice, class: 'alert alert-success') if flash.notice
  .col-lg-1
    %h2
      - if current_user.icon
        = image_tag current_user.icon, size: '80'
      - else
        = image_tag 'prof_noimage_upload.gif', size: '80'
  .col-lg-10
    %h2
      = current_user.username
      さんの本棚
.row
  .col-lg-8
    .page-header
      %h3 本棚
    #shelf
      .shelf-wrapper
        #shelf-inner
          - @items.each_with_index do |item, index|
            .item-wrapper
              .item-area
                .item-img-area
                  = link_to image_tag(small_book_image(item.book.image)), edit_user_item_path(current_user, item)
              - if item.rank > 0
                .rank-icon
                  = rank_to_star(item.rank)
      = paginate @items

app/views/items/search.html.haml
- books = set_books(@data)
- @pager_data = set_pager(@data)
.row
  .col-lg-8
    %h2 "#{@keyword}"での検索結果一覧
    %table.table
      %tbody
        - books.each do |book|
          %tr
            %td
              %h4= link_to book[:title], item_path(book[:asin])
              #{book[:author]} / #{book[:publication_date]} / #{book[:price]}
          %tr.active{id: "book_#{book[:asin]}"}
            %td
              .col-lg-3
                = image_tag book[:medium_image]
              .col-lg-6
                - unless Item.joins(:book).where(:user_id => current_user.id, 'books.asin' => book[:asin]).exists?
                  .regist-btn
                    = form_tag(user_items_path(current_user), {data: {remote: true}, :class => 'result-form'}) do
                      = hidden_field :book, :asin, :value => book[:asin]
                      = hidden_field :book, :title, :value => book[:title]
                      = hidden_field :book, :author, :value => book[:author]
                      = hidden_field :book, :price, :value => book[:price]
                      = hidden_field :book, :manufacturer, :value => book[:manufacturer]
                      = hidden_field :book, :publicated_at, :value => book[:publication_date]
                      = hidden_field :book, :image, :value => book[:image]
                      = submit_tag 'Save', class: 'btn btn-primary'
                - else
                  本棚に登録済み
    = render 'items/pager'

app/views/items/show.html.haml
.row
  .col-lg-12
    .page-header
      %h3 本の詳細
    %h2= @book.title
    .col-lg-5
      = image_tag @book.image
    .col-lg-6
      - if @book.present?
        %h4
          %strong= @book.registered_count
          人登録
        - if @book.has_rank?
          %h4
            %strong= @book.rank
            評価
        %h4
          - reviews = @book.reviews
          %strong #{reviews.count}
          レビュー
      %p 著者:#{@book.author}
      %p #{@book.price} / #{@book.manufacturer} / #{@book.publicated_at}発売
      = link_to 'Amazon詳細ページへ', 'http://www.amazon.co.jp/dp/' + @book.asin, :class => 'btn btn-primary'
      %br
      %br

.row
  .col-lg-12
    .page-header
      %h2 レビュー
    .review
      - if reviews.present?
        - reviews.each do |item|
          - user = item.user
          .row
            .col-lg-1
              - unless user.icon.blank?
                = image_tag user.icon, size: '80'
              - else
                = image_tag 'prof_noimage_upload.gif', size: '80'
            .col-lg-8
              .panel.panel-default
                .panel-heading
                  #{user.username}さんのレビュー
                  - if item.rank > 0
                    .rank-icon
                      = rank_to_star(item.rank)
                .panel-body
                  = item.review
                  %br
                  %p.date.text-muted= item.created_at.strftime("%Y年%m月%d日 %H時%M分%S秒")